/**
 * Copyright (c) 2014,2015 Enzien Audio, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE SECTION6 HEAVY COMPILER.
 */

#ifndef _HEAVYCONTEXT_TABLEREADER_H_
#define _HEAVYCONTEXT_TABLEREADER_H_

#include "HvBase.h"

#define Context(_x) ((Hv_TableReader *) (_x))

// object includes
#include "ControlSystem.h"
#include "SignalVar.h"
#include "ControlCast.h"
#include "SignalSample.h"
#include "HvTable.h"
#include "ControlSlice.h"
#include "SignalTabread.h"
#include "HeavyMath.h"
#include "ControlBinop.h"
#include "ControlVar.h"
#include "ControlDelay.h"
#include "SignalBiquad.h"

typedef struct Hv_TableReader {
  HvBase base;

  // objects
  SignalVarf sVarf_uMI14;
  SignalSample sSample_SRUiE;
  SignalVarf sVarf_Zs21S;
  SignalVarf sVarf_YTMw1;
  SignalVarf sVarf_Fj8rS;
  SignalVarf sVarf_nWA6q;
  SignalTabread sTabread_JAeEX;
  SignalVarf sVarf_ugsRf;
  SignalTabread sTabread_YThVE;
  SignalVarf sVarf_YlOJ5;
  SignalVarf sVarf_c16yw;
  SignalBiquad_k sBiquad_k_MjKyC;
  ControlVar cVar_Usto5;
  ControlBinop cBinop_CDtNk;
  ControlBinop cBinop_YzHbW;
  ControlBinop cBinop_ggtps;
  ControlDelay cDelay_6y36J;
  ControlVar cVar_UVosB;
  ControlVar cVar_jhnl3;
  ControlBinop cBinop_ev4vT;
  ControlSlice cSlice_VRRiQ;
  ControlVar cVar_wQArL;
  ControlBinop cBinop_8oKs3;
  ControlBinop cBinop_oep23;
  ControlBinop cBinop_DyuTh;
  ControlBinop cBinop_OLKAt;
  ControlVar cVar_DuenU;
  ControlBinop cBinop_CW2QZ;
  ControlBinop cBinop_8RmuW;
  ControlBinop cBinop_2ltNh;
  ControlBinop cBinop_OfsHL;
  ControlBinop cBinop_CD1aX;
  ControlBinop cBinop_YF9KN;
  HvTable hTable_apwUK;
} Hv_TableReader;

#endif // _HEAVYCONTEXT_TABLEREADER_H_
