/**
 * Copyright (c) 2014,2015 Enzien Audio, Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, and/or
 * sublicense copies of the Software, strictly on a non-commercial basis,
 * and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 * DO NOT MODIFY. THIS CODE IS MACHINE GENERATED BY THE SECTION6 HEAVY COMPILER.
 */

/*
 * System Includes
 */

#include <assert.h>
#include <math.h>
#include <string.h>
#include <stdarg.h>
#include "HvContext_TableReader.h"
#include "HeavyMath.h"


/*
 * Function Declarations
 */
static void cCast_AIxf0_sendMessage(HvBase *, int, const HvMessage *const);
static void cReceive_GoQYf_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_AtvL4_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_ZjG1g_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_Usto5_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_CDtNk_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_MriUS_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_YzHbW_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_ggtps_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_Vwx46_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_kgVlr_sendMessage(HvBase *, int, const HvMessage *const);
static void cDelay_6y36J_sendMessage(HvBase *, int, const HvMessage *const);
static void cSwitchcase_lVtzk_onMessage(HvBase *, void *, int letIn, const HvMessage *const, void *);
static void cCast_KPjLb_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_kgKLi_sendMessage(HvBase *, int, const HvMessage *const);
static void cSend_uAWFx_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_UVosB_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_jhnl3_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_ev4vT_sendMessage(HvBase *, int, const HvMessage *const);
static void cSlice_VRRiQ_sendMessage(HvBase *, int, const HvMessage *const);
static void cSwitchcase_p3AtP_onMessage(HvBase *, void *, int letIn, const HvMessage *const, void *);
static void cMsg_cENjV_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_7vgPK_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_FScnw_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_wQArL_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_b0Aqa_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_8oKs3_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_oep23_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_DyuTh_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_OLKAt_sendMessage(HvBase *, int, const HvMessage *const);
static void cLoadbang_kZe8t_sendMessage(HvBase *, int, const HvMessage *const);
static void cVar_DuenU_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_CW2QZ_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_8RmuW_sendMessage(HvBase *, int, const HvMessage *const);
static void cMsg_2Wp5b_sendMessage(HvBase *, int, const HvMessage *const);
static void cSystem_TjmcP_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_2ltNh_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_OfsHL_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_CD1aX_sendMessage(HvBase *, int, const HvMessage *const);
static void cBinop_YF9KN_sendMessage(HvBase *, int, const HvMessage *const);
static void sSample_SRUiE_sendMessage(HvBase *, int, const HvMessage *const);
static void cCast_36fKI_sendMessage(HvBase *, int, const HvMessage *const);
static void hTable_apwUK_sendMessage(HvBase *, int, const HvMessage *const);



/*
 * Static Helper Functions
 */

static void ctx_intern_scheduleMessageForReceiver(
    HvBase *const _c, const char *name, HvMessage *m) {
  switch (msg_symbolToHash(name)) {
    case 0xBAE67279: { // SetBufferSize
      ctx_scheduleMessage(_c, m, &cReceive_GoQYf_sendMessage, 0);
      break;
    }
    default: return;
  }
}

static struct HvTable *ctx_intern_getTableForHash(HvBase *const _c, hv_uint32_t h) {
  switch (h) {
    case 0x1443F360: return &Context(_c)->hTable_apwUK; // table
    default: return NULL;
  }
}



/*
 * Context Include and Implementatons
 */

Hv_TableReader *hv_TableReader_new_with_pool(double sampleRate, int poolKb) {
  hv_assert(sampleRate > 0.0); // can't initialise with sampling rate of 0
  hv_assert(poolKb >= 1); // a message pool of some reasonable size is always needed
  Hv_TableReader *const _c = (Hv_TableReader *) hv_malloc(sizeof(Hv_TableReader));

  Base(_c)->numInputChannels = 1;
  Base(_c)->numOutputChannels = 1;
  Base(_c)->sampleRate = sampleRate;
  Base(_c)->blockStartTimestamp = 0;
  Base(_c)->f_scheduleMessageForReceiver = &ctx_intern_scheduleMessageForReceiver;
  Base(_c)->f_getTableForHash = &ctx_intern_getTableForHash;
  mq_initWithPoolSize(&Base(_c)->mq, poolKb);
  Base(_c)->basePath = NULL;
  Base(_c)->printHook = NULL;
  Base(_c)->sendHook = NULL;
  Base(_c)->userData = NULL;
  Base(_c)->name = "TableReader";

  Base(_c)->numBytes = sizeof(Hv_TableReader);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_uMI14, 256.0f, 0.0f, false);
  Base(_c)->numBytes += sSample_init(&_c->sSample_SRUiE);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_Zs21S, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_YTMw1, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_Fj8rS, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_nWA6q, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sTabread_init(&_c->sTabread_JAeEX, &_c->hTable_apwUK, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_ugsRf, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sTabread_init(&_c->sTabread_YThVE, &_c->hTable_apwUK, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_YlOJ5, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sVarf_init(&_c->sVarf_c16yw, 0.0f, 0.0f, false);
  Base(_c)->numBytes += sBiquad_k_init(&_c->sBiquad_k_MjKyC, 1.0f, 0.0f, 0.0f, 0.0f, 0.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_Usto5, 1.0f);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_CDtNk, 0.0f); // __mul
  Base(_c)->numBytes += cDelay_init(Base(_c), &_c->cDelay_6y36J, 0.0f);
  Base(_c)->numBytes += cVar_init_s(&_c->cVar_UVosB, "table");
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_jhnl3, 0.0f);
  Base(_c)->numBytes += cSlice_init(&_c->cSlice_VRRiQ, 1, 1);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_wQArL, 4096.0f);
  Base(_c)->numBytes += cVar_init_f(&_c->cVar_DuenU, 5.0f);
  Base(_c)->numBytes += cBinop_init(&_c->cBinop_CD1aX, 0.0f); // __div
  Base(_c)->numBytes += hTable_init(&_c->hTable_apwUK, 16387);

  // loadbang
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_Vwx46_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_kZe8t_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_b0Aqa_sendMessage, 0);
  ctx_scheduleMessage(Base(_c), msg_initWithBang(HV_MESSAGE_ON_STACK(1), 0), &cLoadbang_7vgPK_sendMessage, 0);

  return _c;
}

Hv_TableReader *hv_TableReader_new(double sampleRate) {
  return hv_TableReader_new_with_pool(sampleRate, 10); // default to 10KB MessagePool
}

void hv_TableReader_free(Hv_TableReader *_c) {
  hTable_free(&_c->hTable_apwUK);

  hv_free(Base(_c)->basePath);
  mq_free(&Base(_c)->mq); // free queue after all objects have been freed, messages may be cancelled

  hv_free(_c);
}



/*
 * Static Function Implementation
 */
static void cCast_AIxf0_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_uMI14, m);
}

static void cReceive_GoQYf_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cCast_onMessage(_c, HV_CAST_FLOAT, 0, m, &cCast_KPjLb_sendMessage);
  cCast_onMessage(_c, HV_CAST_FLOAT, 0, m, &cCast_AIxf0_sendMessage);
}

static void cSystem_AtvL4_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 1000.0f, 0, m, &cBinop_YzHbW_sendMessage);
}

static void cMsg_ZjG1g_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "samplerate");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_AtvL4_sendMessage);
}

static void cVar_Usto5_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_CDtNk, HV_BINOP_MULTIPLY, 0, m, &cBinop_CDtNk_sendMessage);
}

static void cBinop_CDtNk_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MAX, 1.0f, 0, m, &cBinop_ggtps_sendMessage);
}

static void cMsg_MriUS_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "clear");
  cDelay_onMessage(_c, &Context(_c)->cDelay_6y36J, 0, m, &cDelay_6y36J_sendMessage);
}

static void cBinop_YzHbW_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_CDtNk, HV_BINOP_MULTIPLY, 1, m, &cBinop_CDtNk_sendMessage);
}

static void cBinop_ggtps_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_onMessage(_c, &Context(_c)->cDelay_6y36J, 2, m, &cDelay_6y36J_sendMessage);
}

static void cLoadbang_Vwx46_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_ZjG1g_sendMessage(_c, 0, m);
  cVar_onMessage(_c, &Context(_c)->cVar_Usto5, 0, m, &cVar_Usto5_sendMessage);
}

static void cCast_kgVlr_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_MriUS_sendMessage(_c, 0, m);
  cDelay_onMessage(_c, &Context(_c)->cDelay_6y36J, 0, m, &cDelay_6y36J_sendMessage);
  sSample_onMessage(_c, &Context(_c)->sSample_SRUiE, 1, m);
}

static void cDelay_6y36J_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cDelay_clearExecutingMessage(&Context(_c)->cDelay_6y36J, m);
  cDelay_onMessage(_c, &Context(_c)->cDelay_6y36J, 0, m, &cDelay_6y36J_sendMessage);
  sSample_onMessage(_c, &Context(_c)->sSample_SRUiE, 1, m);
}

static void cSwitchcase_lVtzk_onMessage(HvBase *_c, void *o, int letIn, const HvMessage *const m, void *sendMessage) {
  switch (msg_getHash(m,0)) {
    case 0x0: { // "0.0"
      cMsg_MriUS_sendMessage(_c, 0, m);
      break;
    }
    case 0x7A5B032D: { // "stop"
      cMsg_MriUS_sendMessage(_c, 0, m);
      break;
    }
    default: {
      cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_kgVlr_sendMessage);
      break;
    }
  }
}

static void cCast_KPjLb_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_wQArL, 0, m, &cVar_wQArL_sendMessage);
}

static void cCast_kgKLi_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cSwitchcase_lVtzk_onMessage(_c, NULL, 0, m, NULL);
}

static void cSend_uAWFx_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  if (_c->sendHook != NULL) _c->sendHook(ctx_samplesToMilliseconds(_c, msg_getTimestamp(m)), "BufferIndex", m, ctx_getUserData(_c));
}

static void cVar_UVosB_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_cENjV_sendMessage(_c, 0, m);
}

static void cVar_jhnl3_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 2.0f, 0, m, &cBinop_ev4vT_sendMessage);
}

static void cBinop_ev4vT_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sVarf_onMessage(_c, &Context(_c)->sVarf_nWA6q, m);
}

static void cSlice_VRRiQ_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  switch(letIn) {
    case 0: {
      sTabread_onMessage(_c, &Context(_c)->sTabread_JAeEX, 1, m);
      sTabread_onMessage(_c, &Context(_c)->sTabread_YThVE, 1, m);
      cVar_onMessage(_c, &Context(_c)->cVar_UVosB, 0, m, &cVar_UVosB_sendMessage);
      break;
    }
    case 1: {
      break;
    }
    default: return;
  }
}

static void cSwitchcase_p3AtP_onMessage(HvBase *_c, void *o, int letIn, const HvMessage *const m, void *sendMessage) {
  switch (msg_getHash(m,0)) {
    case 0x3E004DAB: { // "set"
      cSlice_onMessage(_c, &Context(_c)->cSlice_VRRiQ, 0, m, &cSlice_VRRiQ_sendMessage);
      break;
    }
    default: {
      break;
    }
  }
}

static void cMsg_cENjV_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(3);
  msg_init(m, 3, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "table");
  msg_setElementToFrom(m, 1, n, 0);
  msg_setSymbol(m, 2, "size");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_FScnw_sendMessage);
}

static void cLoadbang_7vgPK_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_UVosB, 0, m, &cVar_UVosB_sendMessage);
}

static void cSystem_FScnw_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_SUBTRACT, 2.0f, 0, m, &cBinop_ev4vT_sendMessage);
}

static void cVar_wQArL_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 44100.0f, 0, m, &cBinop_8oKs3_sendMessage);
}

static void cLoadbang_b0Aqa_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_wQArL, 0, m, &cVar_wQArL_sendMessage);
}

static void cBinop_8oKs3_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cCast_onMessage(_c, HV_CAST_FLOAT, 0, m, &cCast_36fKI_sendMessage);
  cCast_onMessage(_c, HV_CAST_BANG, 0, m, &cCast_kgKLi_sendMessage);
}

static void cBinop_oep23_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sBiquad_k_onMessage(&Context(_c)->sBiquad_k_MjKyC, 1, m);
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, -1.0f, 0, m, &cBinop_OLKAt_sendMessage);
}

static void cBinop_DyuTh_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_DIVIDE, 2.0f, 0, m, &cBinop_oep23_sendMessage);
}

static void cBinop_OLKAt_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sBiquad_k_onMessage(&Context(_c)->sBiquad_k_MjKyC, 2, m);
}

static void cLoadbang_kZe8t_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cMsg_2Wp5b_sendMessage(_c, 0, m);
  cVar_onMessage(_c, &Context(_c)->cVar_DuenU, 0, m, &cVar_DuenU_sendMessage);
}

static void cVar_DuenU_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, -6.28319f, 0, m, &cBinop_YF9KN_sendMessage);
}

static void cBinop_CW2QZ_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MAX, 0.0f, 0, m, &cBinop_OfsHL_sendMessage);
}

static void cBinop_8RmuW_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  sBiquad_k_onMessage(&Context(_c)->sBiquad_k_MjKyC, 4, m);
}

static void cMsg_2Wp5b_sendMessage(HvBase *_c, int letIn, const HvMessage *const n) {
  HvMessage *m = NULL;
  m = HV_MESSAGE_ON_STACK(1);
  msg_init(m, 1, msg_getTimestamp(n));
  msg_setSymbol(m, 0, "samplerate");
  cSystem_onMessage(_c, NULL, 0, m, &cSystem_TjmcP_sendMessage);
}

static void cSystem_TjmcP_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_CD1aX, HV_BINOP_DIVIDE, 1, m, &cBinop_CD1aX_sendMessage);
}

static void cBinop_2ltNh_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MULTIPLY, -1.0f, 0, m, &cBinop_8RmuW_sendMessage);
  cBinop_k_onMessage(_c, NULL, HV_BINOP_ADD, 1.0f, 0, m, &cBinop_DyuTh_sendMessage);
}

static void cBinop_OfsHL_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_MIN, 1.0f, 0, m, &cBinop_2ltNh_sendMessage);
}

static void cBinop_CD1aX_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_k_onMessage(_c, NULL, HV_BINOP_ADD, 1.0f, 0, m, &cBinop_CW2QZ_sendMessage);
}

static void cBinop_YF9KN_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cBinop_onMessage(_c, &Context(_c)->cBinop_CD1aX, HV_BINOP_DIVIDE, 0, m, &cBinop_CD1aX_sendMessage);
}

static void sSample_SRUiE_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cSend_uAWFx_sendMessage(_c, 0, m);
}

static void cCast_36fKI_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
  cVar_onMessage(_c, &Context(_c)->cVar_Usto5, 0, m, &cVar_Usto5_sendMessage);
}

static void hTable_apwUK_sendMessage(HvBase *_c, int letIn, const HvMessage *const m) {
}




/*
 * Context Process Implementation
 */

int hv_TableReader_process(Hv_TableReader *const _c, float **const inputBuffers, float **const outputBuffers, int nx) {
  const int n4 = nx & ~HV_N_SIMD_MASK; // ensure that the block size is a multiple of HV_N_SIMD

  // temporary signal vars
  hv_bufferf_t Bf0, Bf1, Bf2, Bf3, Bf4;
  hv_bufferi_t Bi0, Bi1;

  // input and output vars
  hv_bufferf_t O0;
  hv_bufferf_t I0;

  // declare and init the zero buffer
  hv_bufferf_t ZERO; __hv_zero_f(VOf(ZERO));

  hv_uint32_t nextBlock = Base(_c)->blockStartTimestamp;
  for (int n = 0; n < n4; n += HV_N_SIMD) {

    // process all of the messages for this block
    nextBlock += HV_N_SIMD;
    while (mq_hasMessageBefore(&Base(_c)->mq, nextBlock)) {
      MessageNode *const node = mq_peek(&Base(_c)->mq);
      node->sendMessage(Base(_c), node->let, node->m);
      mq_pop(&Base(_c)->mq);
    }

    // load input buffers
    __hv_load_f(inputBuffers[0]+n, VOf(I0));// zero output buffers
    __hv_zero_f(VOf(O0));

    // process all signal functions
    __hv_var_f(&_c->sVarf_uMI14, VOf(Bf0));
    __hv_var_k_f(VOf(Bf1), 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0);
    __hv_fma_f(VIf(I0), VIf(Bf0), VIf(Bf1), VOf(Bf1));
    __hv_sample_f(Base(_c), &_c->sSample_SRUiE, VIf(Bf1), &sSample_SRUiE_sendMessage);
    __hv_var_f(&_c->sVarf_Zs21S, VOf(Bf0));
    __hv_var_f(&_c->sVarf_YTMw1, VOf(Bf2));
    __hv_var_f(&_c->sVarf_Fj8rS, VOf(Bf3));
    __hv_add_f(VIf(Bf1), VIf(Bf3), VOf(Bf3));
    __hv_var_f(&_c->sVarf_nWA6q, VOf(Bf4));
    __hv_min_f(VIf(Bf3), VIf(Bf4), VOf(Bf4));
    __hv_add_f(VIf(Bf2), VIf(Bf4), VOf(Bf4));
    __hv_var_k_f(VOf(Bf2), 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0);
    __hv_max_f(VIf(Bf4), VIf(Bf2), VOf(Bf2));
    __hv_cast_fi(VIf(Bf2), VOi(Bi0));
    __hv_var_k_i(VOi(Bi1), 1, 1, 1, 1, 1, 1, 1, 1, 0);
    __hv_add_i(VIi(Bi0), VIi(Bi1), VOi(Bi1));
    __hv_tabread_if(&_c->sTabread_JAeEX, VIi(Bi1), VOf(Bf4));
    __hv_var_f(&_c->sVarf_ugsRf, VOf(Bf3));
    __hv_add_f(VIf(Bf4), VIf(Bf3), VOf(Bf3));
    __hv_tabread_if(&_c->sTabread_YThVE, VIi(Bi0), VOf(Bf4));
    __hv_sub_f(VIf(Bf3), VIf(Bf4), VOf(Bf3));
    __hv_add_f(VIf(Bf0), VIf(Bf3), VOf(Bf3));
    __hv_var_f(&_c->sVarf_YlOJ5, VOf(Bf0));
    __hv_add_f(VIf(Bf0), VIf(Bf2), VOf(Bf0));
    __hv_floor_f(VIf(Bf2), VOf(Bf2));
    __hv_sub_f(VIf(Bf0), VIf(Bf2), VOf(Bf2));
    __hv_var_f(&_c->sVarf_c16yw, VOf(Bf0));
    __hv_add_f(VIf(Bf4), VIf(Bf0), VOf(Bf0));
    __hv_fma_f(VIf(Bf3), VIf(Bf2), VIf(Bf0), VOf(Bf0));
    __hv_biquad_k_f(&_c->sBiquad_k_MjKyC, VIf(Bf0), VOf(Bf0));
    __hv_add_f(VIf(Bf0), VIf(O0), VOf(O0));

    // save output vars to output buffer
    __hv_store_f(outputBuffers[0]+n, VIf(O0));
  }

  Base(_c)->blockStartTimestamp = nextBlock;

  return n4; // return the number of frames processed
}

int hv_TableReader_process_inline(Hv_TableReader *c, float *const inputBuffers, float *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int i = ctx_getNumInputChannels(Base(c));
  float **bIn = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bIn[i] = inputBuffers+(i*n4);

  i = ctx_getNumOutputChannels(Base(c));
  float **bOut = (float **) hv_alloca(i*sizeof(float *));
  while (i--) bOut[i] = outputBuffers+(i*n4);

  int n = hv_TableReader_process(c, bIn, bOut, n4);
  return n;
}

int hv_TableReader_process_inline_short(Hv_TableReader *c, short *const inputBuffers, short *const outputBuffers, int n4) {
  hv_assert(!(n4 & HV_N_SIMD_MASK)); // ensure that n4 is a multiple of HV_N_SIMD
  int numChannels = ctx_getNumInputChannels(Base(c));
  float *bIn = (float *) hv_alloca(numChannels*n4*sizeof(float));
  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      bIn[i*n4+j] = ((float) inputBuffers[i+numChannels*j]) * 0.00003051757813f;
    }
  }

  numChannels = ctx_getNumOutputChannels(Base(c));
  float *bOut = (float *) hv_alloca(numChannels*n4*sizeof(float));

  int n = hv_TableReader_process_inline(c, bIn, bOut, n4);

  for (int i = 0; i < numChannels; ++i) {
    for (int j = 0; j < n4; ++j) {
      outputBuffers[i+numChannels*j] = (short) (bOut[i*n4+j] * 32767.0f);
    }
  }

  return n;
}
